### ISSUE TITLE
FIRST_TIME_RUNNING setting is error-prone

### ISSUE THREAD

**Issue by ForrestTrepte** [microsoft/FMU-bonsai-connector#15]
It is easy to forget to set `FIRST_TIME_RUNNING = False` when creating a docker container and then your simulator won't start. Or it's easy to temporarily change this value and then check it in when you didn't mean to.

Can we eliminate this setting? If a conf.yaml file already exists then we use it and assume its settings are correct. If the config file doesn't exist then we prompt and create it?

**Comment by ChrisKahrs** [comment]
I don't think close_model in FMU_Connector.py is ever called. Or if it is, it isn't called in a try/catch block if there is a keyboard interrupt or any error.  This leaves the process running in memory, which requires a ctl-alt-del to start task manager and kill it manually.  This is also the only way to remove the expanded .zip content as the process has a lock on it.  Thank you!

**Comment by ForrestTrepte** [comment]
@ChrisKahrs, is the close_model issue related to the FIRST_TIME_RUNNING setting? If not, could you please open a new issue to represent that as a separate problem?

**Comment by ChrisKahrs** [comment]
Oh shoot, sorry just getting use to posting bugs in here, I thought it was a new issue, but I see now how it works.  Thanks!
