### ISSUE TITLE
environment.yml and requirements.txt have different packages/versions

### ISSUE THREAD

**Issue by ForrestTrepte** [microsoft/FMU-bonsai-connector#19]
The [environment.yml](https://github.com/microsoft/FMU-bonsai-connector/blob/main/environment.yml) and the [samples/vanDerPol/requirements.txt](https://github.com/microsoft/FMU-bonsai-connector/blob/main/samples/vanDerPol/requirements.txt) files seem like they have similar purposes. But they include a different set of packages and the same packages have different versions.

Could we just use one or the other of these files? Or both these forms are included for convenience of setting up environments then can we give them the same packages with the same versions?

**Comment by ForrestTrepte** [comment]
@juanvergaramunoz: What do you think? I'm happy be happy to make the change if you can recommend which approach we should take. If we want to keep both files, which packages/versions do you think are correct and which should be changed?

**Comment by ChrisKahrs** [comment]
We have these in sync now.  Should we close this?

**Comment by ForrestTrepte** [comment]
Yes. This is resolved by #26. Nice!
